# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Denture KPI Datasheet'
subtitle: 'Manual for using the Denture KPI Datasheet'
email: dr.tingtp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for Denture KPI Datasheet Add-on
baseurl: "/sheets-kpi-dentur" # the subpath of your site, e.g. /blog
url: "https://drtingtp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  drtingtp

# Build settings
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# default front matter properties
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/drtingtp/sheets-kpi-dentur'

header_pages:
  - pages/about.md
  - pages/installation.md
  - pages/usage.md
  - changelog.md